stages:
  load_data:
    cmd: python src/loading.py
    deps:
      - src/loading.py
      - data/raw
    outs:
      - data/processed/train_dataset.h5
      - data/processed/val_dataset.h5
      - data/processed/test_dataset.h5


  train_model:
    cmd: python src/train.py
    deps:
      - data/processed/train_dataset
      - data/processed/val_dataset
      - model.py
      - params.yaml
    outs:
      - model.h5

  evaluate_model:
    cmd: python src/train.py  # Update this to a dedicated evaluation script if necessary
    deps:
      - model.h5
      - data/processed/test_dataset
